version: '3'

services:

  server_mongo_database:
    image: mongo:latest
    container_name: db
    env_file:
      - .env
    volumes:
      - ./data:/data/db
    restart: always
    ports:
      - "27017:27017"

#  server_redis_database:
#    image: redis:latest
#    container_name: server_redis_database
#    env_file:
#      - .env
#    volumes:
#      - ./redis_data:/data
#    restart: always
#    expose:
#      - "6379"
#    ports:
#      - "6379:6379"

  api:
    container_name: api
    build: .
    ports:
      - "80:80"
    env_file:
      - server.env